import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { SupplierStatus } from '@prisma/client';
import { Type } from 'class-transformer';
import {
  IsEmail,
  IsEnum,
  IsInt,
  IsNotEmpty,
  IsOptional,
  IsString,
  Min,
} from 'class-validator';

// Only Supplier Name is required — every other field is optional, per scope.
// supplierCode is deliberately absent here: it is always auto-generated by
// SuppliersService.generateSupplierCode(), never accepted from the client,
// the same convention as Lead.leadNumber.
export class CreateSupplierDto {
  @ApiProperty({ example: 'Tata Steel Ltd.' })
  @IsString()
  @IsNotEmpty({ message: 'Supplier name is required' })
  supplierName: string;

  @ApiPropertyOptional({ example: '27AAACT2727Q1ZW' })
  @IsOptional()
  @IsString()
  gstNumber?: string;

  @ApiPropertyOptional({ example: 'AAACT2727Q' })
  @IsOptional()
  @IsString()
  panNumber?: string;

  @ApiPropertyOptional({ example: 'Ramesh Kumar' })
  @IsOptional()
  @IsString()
  contactPerson?: string;

  @ApiPropertyOptional({ example: '9876543210' })
  @IsOptional()
  @IsString()
  phone?: string;

  @ApiPropertyOptional({ example: 'purchase@tatasteel.com' })
  @IsOptional()
  @IsEmail(undefined, { message: 'Email must be a valid email address' })
  email?: string;

  @ApiPropertyOptional({ example: 'https://www.tatasteel.com' })
  @IsOptional()
  @IsString()
  website?: string;

  @ApiPropertyOptional({ example: 'Plot 12, MIDC Industrial Area' })
  @IsOptional()
  @IsString()
  address?: string;

  @ApiPropertyOptional({ example: 'Pune' })
  @IsOptional()
  @IsString()
  city?: string;

  @ApiPropertyOptional({ example: 'Maharashtra' })
  @IsOptional()
  @IsString()
  state?: string;

  @ApiPropertyOptional({ example: 'India' })
  @IsOptional()
  @IsString()
  country?: string;

  @ApiPropertyOptional({ example: '411019' })
  @IsOptional()
  @IsString()
  pinCode?: string;

  @ApiPropertyOptional({ example: 'Net 30' })
  @IsOptional()
  @IsString()
  paymentTerms?: string;

  @ApiPropertyOptional({ example: 7, description: 'Days until goods arrive after an order is placed' })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(0, { message: 'Lead time cannot be negative' })
  leadTime?: number;

  @ApiPropertyOptional({ example: 'INR' })
  @IsOptional()
  @IsString()
  currency?: string;

  @ApiPropertyOptional({ example: 'Preferred supplier for raw steel' })
  @IsOptional()
  @IsString()
  remarks?: string;

  @ApiPropertyOptional({ enum: SupplierStatus, default: SupplierStatus.ACTIVE })
  @IsOptional()
  @IsEnum(SupplierStatus)
  status?: SupplierStatus = SupplierStatus.ACTIVE;
}
